language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3.24
  - 7.4

sudo: false
dist: trusty

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "YVNrq7TFQ8ZF29bV9cLeq9ik3Dqrsi+vxeaV1cK/7biDKB9XAUruAk/vJAWCSEBadpEey4VHVLlPxoqcf0bp1nwCD785r7zCh0fntgSP8F8DcH6dqWBDNyRyJ2i6nkE90TpL4iGvmaY1z15u5G8DgXqW+qAneAH586vtEFZXrTA="
    - GIT_COMMITTER_NAME=s-nakajima
    - GIT_COMMITTER_EMAIL=nakajimashouhei@gmail.com
    - GIT_AUTHOR_NAME=s-nakajima
    - GIT_AUTHOR_EMAIL=nakajimashouhei@gmail.com

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
